---
- name: include os variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install ntp
  package:
    name: ntp
    state: present

- name: install tzdata
  package:
    name: "{{ ntp_tzdata_package }}"
    state: present
  when: ansible_system == "Linux"

- name: set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: set rtc 0
  command: timedatectl set-local-rtc 0

- name: configure /etc/ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ntp

- name: start and enable ntp service
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: yes
